image: python:3.6-slim-jessie

before_script:
  - apt update && apt install -y libglib2.0 libsm6 libxext6 libxrender1
  - pip install pytest opencv-python


stages:
  - unit_test
  - integration_test


pytest_unit_tests:
  stage: unit_test
  script:
  - pytest unit_tests

pytest_integration_test:
  stage: integration_test
  script:
  - apt install -y git
  - git clone https://gitlab.com/design3-equipe6/photos.git
  - mv photos fig
  - pytest interation_test


