image: python:3.6-slim-jessie

before_script:
  - apt update && apt install -y libglib2.0 libsm6 libxext6 libxrender1
  - pip install pytest opencv-python


stages:
  - unittest
  - itest


pytest_unit_tests:
  stage: unittest
  script:
  - pytest tests


