image_path : /home/willvalin/Pictures/caliibration.table404.2018.png
camera_calibration : ../../resources/calibration/table6_2018-03-21.yml
id : 25
size : 16.35
output_file : ../../resources/calibration/world_calibration_6.npy