image_path : /home/jgilbert/Pictures/vision/2018-02-19/table4Robot/0.jpg
camera_calibration : ../../resources/calibration/table4_2018-03-01.yml
id : 25
size : 16.35
output_file : ../../resources/calibration/world_calibration_4.npy