image_path : /home/willvalin/Pictures/table2calibration.png
camera_calibration : ../../resources/calibration/table2_2018-03-21.yml
id : 25
size : 16.35
output_file : ../../resources/calibration/world_calibration_2.npy