%YAML 1.1
---

port: &port 7420
log_dir: "log"
log_file: "log/{date}.log"

robot:
  network:
    host_ip: "127.0.0.1"
    port: *port

station:
  update_robot: false
  resources_path:
    countries_list: "resources/countries/A-Liste_UTF-16.txt"
    country_flag: "resources/countries/Flag_{country}.gif"
    ui: "src/ui/untitled.ui"
  network:
    port: *port
