%YAML 1.1
---

port: &port 7420
log_dir: "log"
log_file: "log/{date}.log"

robot:
  network:
    host_ip: "10.42.0.190"
    port: *port
  serial:
    port: "/dev/ttyUSB0"


station:
  update_robot: true
  resources_path:
    countries_list: "resources/countries/A-Liste_UTF-16.txt"
    country_flag: "resources/countries/Flag_{country}.gif"
    ui: "src/ui/main_windows.ui"
  network:
    port: *port
