%YAML 1.1
---

port: &port 7420
log_dir: "log"
log_file: "log/{date}.log"

robot:
  network:
    host_ip: "10.42.0.78"
    port: *port
  serial:
    port: "/dev/ttyUSB0"

station:
  distance_between_robot_center_and_cube_center: 18 #cm
  table_number: 4
  resources_path:
    countries_list: "resources/countries/A-Liste_UTF-16.txt"
    country_flag: "resources/countries/Flag_{country}.gif"
    ui: "src/ui/main_windows.ui"
    camera_calibration:
      - "resources/calibration/table1_2018-03-21.yml"
      - "resources/calibration/table2_2018-03-21.yml"
      - "resources/calibration/table3_2018-03-21.yml"
      - "resources/calibration/table4_2018-03-01.yml"
      - "resources/calibration/table5_2018-03-21.yml"
      - "resources/calibration/table6_2018-03-21.yml"
    world_calibration:
      - ""
      - "resources/calibration/world_calibration_2.npy"
      - "resources/calibration/world_calibration_3.npy"
      - "resources/calibration/world_calibration_4.npy"
      - ""
      - "resources/calibration/world_calibration_6.npy"
  camera:
    use_mocked_camera: true
    mocked_camera_image_path: "fig/saved_images/table2/00h02m31s.jpg"
    camera_id: 1
    image_width: 1600
    image_height: 1200
    image_save_dir: "fig/{date}"
  network:
    use_mocked_network: true
    mocked_country_code: 59
    port: *port
  robot:
    use_mocked_robot_detector: true
    mocked_robot_position:
      - 15
      - 15
    mocked_robot_orientation: 45
    update_robot: false
  cube_positions:
    tables:
      target_zone:
        length: 66.2
      t2:
        cube0:
          x: 166.5
          y: 84.5
          pixel_x: 1360
          pixel_y: 240
        cube1:
          x: 180.5
          y: 84.5
          pixel_x: 1424
          pixel_y: 240
        cube2:
          x: 203.5
          y: 60.5
          pixel_x: 1575
          pixel_y: 402
        cube3:
          x: 203.5
          y: 46.5
          pixel_x: 1575
          pixel_y: 501
        cube4:
          x: 203.5
          y: 32.5
          pixel_x: 1575
          pixel_y: 600
        cube5:
          x: 203.5
          y: 18.5
          pixel_x: 1575
          pixel_y: 700
        cube6:
          x: 203.5
          y: 4.5
          pixel_x: 1575
          pixel_y: 800
        cube7:
          x: 180.5
          y: -19.5
          pixel_x: 1424
          pixel_y: 960
        cube8:
          x: 166.5
          y: -19.5
          pixel_x: 1350
          pixel_y: 960
