%YAML 1.1
---

port: &port 7420
log_dir: "log"
log_file: "log/{date}.log"

robot:
  network:
    host_ip: "127.0.0.1"
    port: *port
  serial:
    port: "/dev/ttyUSB0"
  distance_between_robot_center_and_cube_center: 18 #cm

station:
  table_number: 2
  resources_path:
    countries_list: "resources/countries/A-Liste_UTF-16.txt"
    country_flag: "resources/countries/Flag_{country}.gif"
    ui: "src/ui/main_windows.ui"
    camera_calibration:
      - "resources/calibration/table1_2018-03-21.yml"
      - "resources/calibration/table2_2018-03-21.yml"
      - "resources/calibration/table3_2018-03-21.yml"
      - "resources/calibration/table4_2018-03-01.yml"
      - "resources/calibration/table5_2018-03-21.yml"
      - "resources/calibration/table6_2018-03-21.yml"
    world_calibration:
      - ""
      - "resources/calibration/world_calibration_2.npy"
      - "resources/calibration/world_calibration_3.npy"
      - "resources/calibration/world_calibration_4.npy"
      - ""
      - "resources/calibration/world_calibration_6.npy"
  camera:
    use_mocked_camera: false
    mocked_camera_image_path: "fig/saved_images/table5/13h48m53s.jpg"
    camera_id: 0
    image_width: 1600
    image_height: 1200
    image_save_dir: "fig/{date}"
  network:
    use_mocked_network: true
    port: *port
  update_robot: false

cube_positions:
  table2:
    cube1:
      x:166.5
      y:84.5
    cube2:
      x:180.5
      y:84.5
    cube3:
      x:203.5
      y:60.5
    cube4:
      x:203.5
      y:46.5
    cube5:
      x:203.5
      y:32.5
    cube6:
      x:203.5
      y:18.5
    cube7:
      x:203.5
      y:4.5
    cube8:
      x:180.5
      y:-19.5
    cube1:
      x:166.5
      y:-19.5
