%YAML 1.1
---

port: &port 7420
log_dir: "log"
log_file: "log/{date}.log"

robot:
  network:
    host_ip: "127.0.0.1"
    port: *port
  serial:
    port: "/dev/ttyUSB0"


station:
  table_number: 4
  update_robot: false
  resources_path:
    countries_list: "resources/countries/A-Liste_UTF-16.txt"
    country_flag: "resources/countries/Flag_{country}.gif"
    ui: "src/ui/main_windows.ui"
    camera_calibration:
      - "resources/calibration/table1_2018-03-21.yml"
      - "resources/calibration/table2_2018-03-21.yml"
      - "resources/calibration/table3_2018-03-21.yml"
      - "resources/calibration/table4_2018-03-01.yml"
      - "resources/calibration/table5_2018-03-21.yml"
      - "resources/calibration/table6_2018-03-21.yml"
    world_calibration:
      - ""
      - ""
      - ""
      - "resources/calibration/world_calibration_4.npy"
      - ""
      - ""
  camera:
    use_mocked_camera: true
    mocked_camera_image_path: "fig/saved_images/table5/13h48m53s.jpg"
    camera_id: 1
  network:
    port: *port
