WORLD_CAM_LOG_DIR = '../../log/'
WORLD_CAM_LOG_FILE = WORLD_CAM_LOG_DIR + 'world_cam.log'
WORLD_CAM_CALIBRATION_DIR = '../../resources/calibration/'
WORLD_CAM_CALIBRATION_OUTPUT = WORLD_CAM_CALIBRATION_DIR + 'world_cam_calibration_output.npz'
ENVIRONMENT_LOG_DIR = '../../log/'
ENVIRONMENT_LOG_FILE = ENVIRONMENT_LOG_DIR + 'environment.log'
MAIN_CONTROLLER_LOG_DIR = '../../log/'
MAIN_CONTROLLER_LOG_FILE = ENVIRONMENT_LOG_DIR + 'main_controller.log'
FIG_DIRECTORY = "../../fig/"
